HEAD = SoftwareSerial.h
# No source for this very short dummy library
PACK = ../pack/

.PHONY: install

install:
	# Copying SoftwareSerial emulator header file
	cp $(HEAD) $(PACK)
	# Done copying SoftwareSerial emulator files
